version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - personal-web-data:/var/lib/pg
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: personal_web
      POSTGRES_USER: postgres
    ports:
      - 8102:5432
  rails_app:
    build:
      context: /Users/olivercai/Desktop/projects/personal_web
      dockerfile: 'Dockerfile.rails'
      args:
        runtime_environment: ${runtime_environment}
    ports:
      - "3000:3000"
    environment:
      - RAILS_LOG_TO_STDOUT=1
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    depends_on:
      - postgres
    

volumes:
  personal-web-data: